plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\giada\\Documents\\antigravity\\splendid-nobel\\disney-pixar-tracker\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\giada\\Documents\\antigravity\\splendid-nobel\\disney-pixar-tracker"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]