export const POSTER_MAP = {
  'Biancaneve e i sette nani': 'https://image.tmdb.org/t/p/w500/qpHDBFBYpxeNbFzqBHNlDlfzmj7.jpg',
  'Pinocchio': 'https://image.tmdb.org/t/p/w500/nMtQF5RuqXQkzRvqJhR4e5rVi5K.jpg',
  'Fantasia': 'https://image.tmdb.org/t/p/w500/kqDeE9s9WoVXVdZ9jKBfmjDlxdC.jpg',
  'Dumbo': 'https://image.tmdb.org/t/p/w500/pTN2ItWSJimElAHWMNK8hpnPbGZ.jpg',
  'Bambi': 'https://image.tmdb.org/t/p/w500/nPFpWGPsLaAmHsLm4B1bO34BSPR.jpg',
  'Cenerentola': 'https://image.tmdb.org/t/p/w500/9n2mwM5PsgVH1cFHaVXmpCJ8gJl.jpg',
  'Alice nel Paese delle Meraviglie': 'https://image.tmdb.org/t/p/w500/or50hkkvHdg3sHMRmIhBNBPdnqe.jpg',
  'Le avventure di Peter Pan': 'https://image.tmdb.org/t/p/w500/kVCHJD4vqVMjDm6WKDf5BKJT7Sk.jpg',
  'Lilli e il vagabondo': 'https://image.tmdb.org/t/p/w500/2uoV4IiEFh9fHZV0qHIJxFrW10I.jpg',
  'La bella addormentata nel bosco': 'https://image.tmdb.org/t/p/w500/yh91oJsf9scqLhNGEKw2N1iQlYx.jpg',
  'La carica dei 101': 'https://image.tmdb.org/t/p/w500/aGr6sEe2A2zLBPCqXMBNO6dJvdp.jpg',
  'La spada nella roccia': 'https://image.tmdb.org/t/p/w500/5lPOGMX8Mhkv1GfHWnbGxuT5Kpz.jpg',
  'Il libro della giungla': 'https://image.tmdb.org/t/p/w500/rhIRbceoE9lR4veEXuwCC2wARtG.jpg',
  'Gli Aristogatti': 'https://image.tmdb.org/t/p/w500/20Fm3N6TrMaBGKIWq3SFPJ4fzVB.jpg',
  'Robin Hood': 'https://image.tmdb.org/t/p/w500/qBFkBHKwSoY9kpg0JJzQqSiKjIg.jpg',
  'Le avventure di Winnie the Pooh': 'https://image.tmdb.org/t/p/w500/9vH4rcDmMU0s6AEcnzPY8e1e5mB.jpg',
  'La sirenetta': 'https://image.tmdb.org/t/p/w500/3cCXpFlKJGkbEiMidHbCUCRbvmh.jpg',
  'La bella e la bestia': 'https://image.tmdb.org/t/p/w500/tWqifoYuwLETmmasnGHO7xBjEtt.jpg',
  'Aladdin': 'https://image.tmdb.org/t/p/w500/oa3eqMeNNHBTKMNGe3nnVLEXgha.jpg',
  'Il re leone': 'https://image.tmdb.org/t/p/w500/vX1x1sPHxIpxPEuXMiGW3VWXnIZ.jpg',
  'Pocahontas': 'https://image.tmdb.org/t/p/w500/gjZksNHrLBBsQwAuBkHlstJxqKB.jpg',
  'Il gobbo di Notre Dame': 'https://image.tmdb.org/t/p/w500/y7MidDlQ8sHbqVPaAF0NN5OW3zP.jpg',
  'Hercules': 'https://image.tmdb.org/t/p/w500/4uoSCmZpNFvnKfC9bM7BKhZGi8n.jpg',
  'Mulan': 'https://image.tmdb.org/t/p/w500/aosm8NMQ3UyoBVpSxyimorCQykC.jpg',
  'Tarzan': 'https://image.tmdb.org/t/p/w500/j5WYQP4dVjZamJQnGWirAHdlcNK.jpg',
  'Lilo e Stitch': 'https://image.tmdb.org/t/p/w500/6GEfY7V2YG5LHsecWI2MVEoAPFj.jpg',
  'Il pianeta del tesoro': 'https://image.tmdb.org/t/p/w500/bXoMdQeQTlvKWaLhiMJLXEX8vSm.jpg',
  'Koda, fratello orso': 'https://image.tmdb.org/t/p/w500/9qCjbkqQrVF0JWFKL1C0J1xELQn.jpg',
  'Frozen - Il regno di ghiaccio': 'https://image.tmdb.org/t/p/w500/iDhseXHBhOBtHHhbFOXOkZMm3pV.jpg',
  'Big Hero 6': 'https://image.tmdb.org/t/p/w500/rPnMPwIR6dvnxYGGVRX4Nso5JlA.jpg',
  'Zootropolis': 'https://image.tmdb.org/t/p/w500/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg',
  'Oceania': 'https://image.tmdb.org/t/p/w500/inVq3FRqcYIRl2la8iZikYYxFNR.jpg',
  'Encanto': 'https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg',
  'Frozen II - Il regno di Arendelle': 'https://image.tmdb.org/t/p/w500/qdfARIhgpgZOBh3vfNhWS4hmSo3.jpg',
  'Wish': 'https://image.tmdb.org/t/p/w500/nRGCKIBBjwBlQFMVePFVw3UJsaI.jpg',
  'Moana 2': 'https://image.tmdb.org/t/p/w500/yiMZ6mgDfhVvjinMRJOAZuWbLZb.jpg',
  'Toy Story - Il mondo dei giocattoli': 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
  'Toy Story 2 - Woody e Buzz alla riscossa': 'https://image.tmdb.org/t/p/w500/sHM3vbkQXHgDHSrGv5RXZMnQeqE.jpg',
  'Toy Story 3 - La grande fuga': 'https://image.tmdb.org/t/p/w500/AbbXspMOwdvwr7nab1JRBHJYlaO.jpg',
  'Toy Story 4': 'https://image.tmdb.org/t/p/w500/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg',
  'Toy Story 5': 'https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
  'Monsters e Co.': 'https://image.tmdb.org/t/p/w500/sgheSKxZkttIe8ONaJXfELFAk7O.jpg',
  'Monsters University': 'https://image.tmdb.org/t/p/w500/jB8PXLysILbjv4HGG5UbxNxHUDq.jpg',
  'Alla ricerca di Nemo': 'https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg',
  'Alla ricerca di Dory': 'https://image.tmdb.org/t/p/w500/3N9W5MHGilclGLCfTfWeMYT4YQd.jpg',
  'Cars - Motori ruggenti': 'https://image.tmdb.org/t/p/w500/tc9aHCJI8RqNT0LlHfDdNwq4qhm.jpg',
  'Cars 2': 'https://image.tmdb.org/t/p/w500/nOrHPSIGPdNmN0UkUPsHIRE0Bst.jpg',
  'Cars 3': 'https://image.tmdb.org/t/p/w500/3UjSFbHciwFRgXNM3RiEHnOaZ0q.jpg',
  'Ratatouille': 'https://image.tmdb.org/t/p/w500/npHNjldbeTHdKKw28bJKs7lzqzj.jpg',
  'WALL-E': 'https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnjefeOy.jpg',
  'Up': 'https://image.tmdb.org/t/p/w500/hhu4fOXtF3l5TU3XkN5nFqOqWQZ.jpg',
  'Brave - Ribelle': 'https://image.tmdb.org/t/p/w500/way3eKnMd8JCfgKhk3yCiVsxJxS.jpg',
  'Inside Out': 'https://image.tmdb.org/t/p/w500/aAmfIX3TT40zUHGcCKrlOZRKC7u.jpg',
  'Inside Out 2': 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
  'Il Viaggio di Arlo': 'https://image.tmdb.org/t/p/w500/qNsYYCMQFYdE2PGcR4Hk4pIWCEe.jpg',
  'Coco': 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
  'Soul': 'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
  'Luca': 'https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg',
  'Red': 'https://image.tmdb.org/t/p/w500/qSb49QyJBdmRqYXXBTL2y1x28Fo.jpg',
  'Lightyear': 'https://image.tmdb.org/t/p/w500/65lmJO2hJJhNZ8SsSwm7LMmqCMV.jpg',
  'Elemental': 'https://image.tmdb.org/t/p/w500/6oH378KUfgdm5mCMdWLAuFaHkXv.jpg',
  'Elio': 'https://image.tmdb.org/t/p/w500/3SfxWhiRq0QF6Fo6lVgNOKQeXgD.jpg',
  'Rapunzel': 'https://image.tmdb.org/t/p/w500/oBFUOnb0MUnItXVNh1mnkzpWJd2.jpg',
  // --- Live Action (titoli esatti dal dataset) ---
  'La carica dei 102': 'https://image.tmdb.org/t/p/w500/aGr6sEe2A2zLBPCqXMBNO6dJvdp.jpg',
  'Alice in Wonderland': 'https://image.tmdb.org/t/p/w500/or50hkkvHdg3sHMRmIhBNBPdnqe.jpg',
  'Maleficent': 'https://image.tmdb.org/t/p/w500/9xfNkPwDOQEGEF9EQeGsEpSBnOG.jpg',
  'Crudelia': 'https://image.tmdb.org/t/p/w500/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
  'Christopher Robin': 'https://image.tmdb.org/t/p/w500/r3eFEcLDSCoxGl6mVKfq1pU01QR.jpg',
  'Lilli e il Vagabondo': 'https://image.tmdb.org/t/p/w500/2uoV4IiEFh9fHZV0qHIJxFrW10I.jpg',
  'Peter Pan & Wendy': 'https://image.tmdb.org/t/p/w500/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
  'Mufasa - Il re leone': 'https://image.tmdb.org/t/p/w500/lurEK87kukWNaHd0zYnsi3yzJrs.jpg',
  'Biancaneve': 'https://image.tmdb.org/t/p/w500/oAa4r45oBMHnAiRtJDGIpzxhZki.jpg',
  'Lilo & Stitch': 'https://image.tmdb.org/t/p/w500/y4AQjkqhK2rnUz4P6YFPNJFB76I.jpg',
};

export function getPosterUrl(movie) {
  const override = POSTER_MAP[movie.title];
  if (override) return override;
  if (movie.poster && movie.poster.startsWith('http')) return movie.poster;
  return null;
}
